%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\maipa\Desktop\patientdata.xlsx
%    Worksheet: Tabelle1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/01/30 12:53:12

%% Import the data
[~, ~, raw] = xlsread('C:\Users\maipa\Desktop\patientdata.xlsx','Tabelle1','A2:L101');
stringVectors = string(raw(:,[1,2,3,4,9]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[5,6,7,8,10,11,12]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
patientdata = table;

%% Allocate imported array to column variable names
DATA.patientdata.ID = stringVectors(:,1);
DATA.patientdata.Vorname = stringVectors(:,2);
DATA.patientdata.Nachname = stringVectors(:,3);
DATA.patientdata.Geschlecht = categorical(stringVectors(:,4));
DATA.patientdata.jahr = data(:,1);
DATA.patientdata.Alter = data(:,2);
DATA.patientdata.Gre = data(:,3);
DATA.patientdata.Gewicht = data(:,4);
DATA.patientdata.HinweisszurMessungmissing = stringVectors(:,5);
DATA.patientdata.BWmeasured = data(:,5);
DATA.patientdata.BHmeasured = data(:,6);
DATA.patientdata.FL_Mocap = data(:,7);

%% Clear temporary variables
clearvars data raw stringVectors;